### ISSUE TITLE
Bump exporter version to 0.3.0

### ISSUE THREAD

**Issue by xtianae7** [idealista/prometheus_oracle_exporter_role#22]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Bump exporter version from 0.2.9 to 0.3.0

https://github.com/iamseth/oracledb_exporter/releases/tag/0.3.0rc1

**Comment by dortegau** [comment]
merged! 👍
